title: Cybersecurity Projects
description: Hacker is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
description: [Built to document my hands-on work and show employers what I can actually do- not just what I studied.]
